Fix weird Rubocop auto-correct issues

diff --git a/lib/omnibus/templates/package_scripts/makeselfinst.erb b/lib/omnibus/templates/package_scripts/makeselfinst.erb
--- a/lib/omnibus/templates/package_scripts/makeselfinst.erb
+++ b/lib/omnibus/templates/package_scripts/makeselfinst.erb
@@ -11,7 +11,7 @@ USAGE="usage: $0"
 
 error_exit()
 {
-  echo "${PROGNAME}: ${1:-"Unknown Error" }" 1>&2
+  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
   exit 1
 }
 
