Add Rubocop

diff --git a/lib/omnibus/templates/package_scripts/postinst.erb b/lib/omnibus/templates/package_scripts/postinst.erb
--- a/lib/omnibus/templates/package_scripts/postinst.erb
+++ b/lib/omnibus/templates/package_scripts/postinst.erb
@@ -8,7 +8,7 @@ PROGNAME=$(basename $0)
 
 function error_exit
 {
-  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
+  echo "${PROGNAME}: ${1:-"Unknown Error" }" 1>&2
   exit 1
 }
 
